language: php

php:
  - 5.4
  - 5.5
  - 5.6.18
  - 7.0
  - hhvm

sudo: false

env:
  - COMPOSER_OPTS=""

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

before_install:
  - composer self-update

install:
  - export BACKEND_HOST=foo
  - export BACKEND_TOKEN=bar
  - travis_retry composer update $COMPOSER_OPTS --no-interaction --prefer-source
